//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Kuznetsov_PR14.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRIL
    {
        public int id { get; set; }
        public string naimenov { get; set; }
        public int kolichestvo { get; set; }
        public decimal cena { get; set; }
        public string GrilID { get; set; }
    
        public virtual Tip Tip { get; set; }
    }
}
